backend:
  name: github
  repo: akshayzoenix/reflections-blog
  branch: main
  auth_scope: repo
  client_id: Ov23liFPuj77LTi8G7YK
  client_secret: b0fbff47722d98132dd9603492ebb8e8d235b143


media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "posts"
    label: "Blog Posts"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
