site_url: "https://sochseshabdtak.com"

backend:
  name: github
  repo: akshayzoenix/reflections-blog
  branch: main
  client_id: Ov23liFPuj77LTi8G7YK

publish_mode: editorial_workflow  # ✅ Enables "Save as Draft" and workflow tab

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "posts"
    label: "Blog Posts"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Date"
        name: "date"
        widget: "datetime"
      - label: "Featured Image"
        name: "featured_image"
        widget: "image"
        required: false
      - label: "Draft"               # ✅ Added this boolean field
        name: "draft"
        widget: "boolean"
        default: false
      - label: "Tags"
        name: "tags"
        widget: "select"
        multiple: true
        options:
          - philosophy
          - cosmos
          - shayari
          - wisdom
        hint: "Select one or more tags that describe this post"
        required: false
      - label: "Body"
        name: "body"
        widget: "markdown"
